name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge main into PR branch
        if: github.event_name == 'pull_request'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin main
          if ! git merge origin/main; then
            echo "Merge failed due to conflicts. Please rebase your branch on main."
            exit 1
          fi

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Nix cache
        uses: cachix/cachix-action@v17
        with:
          name: wrappers
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run checks
        run: nix flake check --log-format bar-with-logs
